### PR TITLE
How about this?

### PR DESCRIPTION
**Pull request by hiraginoyuki**
まって

### CODE REVIEW

**Comment by hiraginoyuki** [comment]
おk

**Comment by hiraginoyuki** [comment]
おk

**Comment by tenzyu** [comment]
おk

**Comment by hiraginoyuki** [comment]
Oh wait this is NOT p  e r f e c t

**Comment by hiraginoyuki** [comment]
https://discord.com/developers/docs/resources/webhook#execute-webhook

**Comment by hiraginoyuki** [comment]
Says that following is required
> one of content, file, embeds

Which means we should have another condition

**Comment by hiraginoyuki** [comment]
https://github.com/mii-community/mii/pull/19

**Pull request merged**
